### ISSUE TITLE
Add client not working

### ISSUE THREAD

**Issue by wiratmoko1708** [ahmadafif-codaff/anmik#1]
hi sir.., I have add client but not add in aplication, please give the solution. thanks

**Comment by ahmadafif-codaff** [comment]
The thing you need to pay attention to is that you have to create a firewall and package so you can create a client. Tell me, are you adding a client for the first time? If it's true, there's no need to worry, actually adding a simple root queue the first time will not be detected in the ANMIK application, and the second time and so on it will be detected in the ANMIK application. You can check MIKROTIK in the /queue/simple menu whether there is an additional simple queue or not.

**Comment by wiratmoko1708** [comment]
Do yo have video tutorial or step by step setting in mikrotik create firewall and package?

**Comment by ahmadafif-codaff** [comment]
Sorry..., there is no video tutorial yet, but I will make one soon. But don't worry, you can follow the tutorial via Readme.
And good news! After I checked again, there is a small bug in the client module so you can't create the client as you said! For now it has been fixed, and you can try again, and of course follow the tutorial in the readme. If there are other bugs, don't hesitate to report back. Thankss

**Comment by wiratmoko1708** [comment]
Thanks
